### ISSUE TITLE
Add ability to set the User-Agent for external sources

### ISSUE THREAD

**Issue by lasconic** [tripviss/image-resizer#30]
It would be very useful to be able to set the user-agent for external sources. Since image-resizer doesn't forward the query parameters and it's best used on Heroku (where there is no fix IP), it's not easy to know on the origin "who" called and make the difference between legitimate and non legitimate calls for example.

**Comment by teohhanhui** [comment]
PR welcome! I think it'd be great if the User-Agent override can be specified at a per-source level.

**Comment by teohhanhui** [comment]
Also, I'd love to hear your experience of using it on Heroku. The Heroku setup is from the (seems to be no longer maintained) original repo (https://github.com/jimmynicol/image-resizer).

Are there changes necessary and what can we do to make it better? (PRs welcome! :smile:)

**Comment by lasconic** [comment]
About Heroku, so far so good. It works out of the box. Performance with a single dyno is not that great.

I can do a PR for a single User-Agent for all sources. Not sure how you would want it to work at a per source level. Hardcode all the current possibilities? TWITTER_USER_AGENT, YOUTUBE_USER_AGENT etc.. ?

**Comment by lasconic** [comment]
PR https://github.com/tripviss/image-resizer/pull/31
